// Journal entries — each has a cover + a set of photos (for the detail grid).
// Placeholder imagery is represented by color + ratio; swap for real files later.

const JOURNALS = [
  {
    id: "j01",
    title: "Hakone, in February",
    place: "Kanagawa, JP",
    date: "2026.02",
    tag: "travel",
    cover: { color: 1, ratio: 1.25 },
    words: "Three cold mornings at the lake. Steam rising from the onsen, a heron standing in the shallows for an hour without moving. Mostly I waited for the fog to lift; mostly it didn't.",
    photos: [
      { color: 1,  ratio: 1.25, label: "lake / 06:42" },
      { color: 4,  ratio: 0.80, label: "cedar"        },
      { color: 2,  ratio: 1.50, label: "onsen steam"  },
      { color: 7,  ratio: 1.00, label: "stones"       },
      { color: 3,  ratio: 1.30, label: "boat"         },
      { color: 6,  ratio: 0.75, label: "heron"        },
      { color: 4,  ratio: 1.20, label: "inn window"   },
      { color: 1,  ratio: 1.10, label: "after dusk"   },
      { color: 2,  ratio: 1.00, label: "tea room"     },
    ],
  },
  {
    id: "j02",
    title: "Yaeyama — film diary",
    place: "Okinawa, JP",
    date: "2025.11",
    tag: "travel",
    cover: { color: 5, ratio: 1.25 },
    words: "Shot entirely on a Mamiya 7 with two rolls of Portra 400. The light on Ishigaki is unlike anything on the mainland — softer, wider, patient. I learned to stop composing and just watch.",
    photos: [
      { color: 5, ratio: 1.20, label: "ishigaki / pier" },
      { color: 3, ratio: 1.50, label: "hibiscus"         },
      { color: 6, ratio: 0.80, label: "reef at low tide" },
      { color: 9, ratio: 1.30, label: "house, blue door" },
      { color: 5, ratio: 1.00, label: "afternoon"        },
      { color: 7, ratio: 1.10, label: "sand, close"      },
      { color: 6, ratio: 1.40, label: "road to taketomi" },
      { color: 3, ratio: 0.75, label: "shiisā"           },
      { color: 9, ratio: 1.20, label: "last roll"        },
      { color: 5, ratio: 0.95, label: "terminal"         },
    ],
  },
  {
    id: "j03",
    title: "Kyoto, after the rain",
    place: "Kyoto, JP",
    date: "2025.09",
    tag: "city",
    cover: { color: 6, ratio: 1.25 },
    words: "A typhoon passed the night before. The streets in Gion were empty at five in the morning, reflections running edge to edge. I kept the shutter slow and let the puddles do the work.",
    photos: [
      { color: 6, ratio: 1.25, label: "gion / 05:12"     },
      { color: 4, ratio: 0.80, label: "alley"            },
      { color: 2, ratio: 1.50, label: "lanterns wet"     },
      { color: 3, ratio: 1.00, label: "shōji"            },
      { color: 8, ratio: 1.20, label: "umbrella"         },
      { color: 6, ratio: 1.30, label: "puddle, reflected"},
      { color: 4, ratio: 0.95, label: "stone steps"      },
      { color: 2, ratio: 1.10, label: "taxi"             },
    ],
  },
  {
    id: "j04",
    title: "Kumano Kodō",
    place: "Wakayama, JP",
    date: "2025.06",
    tag: "travel",
    cover: { color: 10, ratio: 1.25 },
    words: "Four days walking the Nakahechi route. I brought one camera and two rolls and tried not to overshoot. The forest does most of the editing for you — you see what the light allows.",
    photos: [
      { color: 10, ratio: 1.25, label: "nakahechi / day 1" },
      { color: 6,  ratio: 1.50, label: "moss"              },
      { color: 4,  ratio: 0.80, label: "torii"             },
      { color: 10, ratio: 1.10, label: "rest house"        },
      { color: 7,  ratio: 1.00, label: "river, morning"    },
      { color: 6,  ratio: 1.30, label: "forest floor"      },
      { color: 2,  ratio: 0.75, label: "shrine bell"       },
      { color: 10, ratio: 1.20, label: "final descent"     },
    ],
  },
  {
    id: "j05",
    title: "Seto Inland",
    place: "Kagawa, JP",
    date: "2025.04",
    tag: "travel",
    cover: { color: 4, ratio: 1.25 },
    words: "Island-hopping by ferry. Naoshima, Teshima, Inujima. The sea is calm enough that the horizon becomes a drawn line. I photographed the boats more than the art.",
    photos: [
      { color: 4, ratio: 1.25, label: "ferry / teshima" },
      { color: 2, ratio: 0.95, label: "harbor"          },
      { color: 7, ratio: 1.50, label: "pavilion"        },
      { color: 3, ratio: 1.00, label: "bicycle rental"  },
      { color: 4, ratio: 1.20, label: "cat on pier"     },
      { color: 8, ratio: 0.80, label: "lighthouse"      },
      { color: 2, ratio: 1.10, label: "inland sea"      },
      { color: 7, ratio: 1.30, label: "ryokan window"   },
      { color: 3, ratio: 1.00, label: "last ferry"      },
    ],
  },
  {
    id: "j06",
    title: "Midnight service stations",
    place: "Tōhoku, JP",
    date: "2024.11",
    tag: "night",
    cover: { color: 8, ratio: 1.25 },
    words: "A long drive north. I pulled over at every lit-up gas station between Fukushima and Aomori. Fluorescent under a cold sky. Nobody inside, most of the time.",
    photos: [
      { color: 8, ratio: 1.25, label: "fukushima / 01:20" },
      { color: 4, ratio: 0.80, label: "pump"              },
      { color: 2, ratio: 1.50, label: "vending"           },
      { color: 8, ratio: 1.00, label: "office light"      },
      { color: 4, ratio: 1.20, label: "highway, empty"    },
      { color: 2, ratio: 1.30, label: "truck parked"      },
      { color: 8, ratio: 0.95, label: "coffee, 110¥"      },
    ],
  },
  {
    id: "j07",
    title: "Shōnan, 07:12",
    place: "Kanagawa, JP",
    date: "2024.08",
    tag: "coast",
    cover: { color: 9, ratio: 1.25 },
    words: "A quick morning at Kugenuma before work. The surfers were already out. I stayed forty minutes and shot one roll, walked back and caught the Odakyū line at a quarter to eight.",
    photos: [
      { color: 9, ratio: 1.25, label: "kugenuma"        },
      { color: 5, ratio: 1.50, label: "paddle out"      },
      { color: 7, ratio: 0.80, label: "board, sand"     },
      { color: 9, ratio: 1.00, label: "tide line"       },
      { color: 5, ratio: 1.20, label: "enoshima distant"},
      { color: 7, ratio: 1.10, label: "walking back"    },
    ],
  },
  {
    id: "j08",
    title: "Concrete, at noon",
    place: "Osaka, JP",
    date: "2024.05",
    tag: "city",
    cover: { color: 3, ratio: 1.25 },
    words: "An afternoon in Nishinari, then Umeda. Hard shadows, hotter than expected. I drank two cans of coffee and walked until my shirt was stuck to my back.",
    photos: [
      { color: 3, ratio: 1.25, label: "nishinari"      },
      { color: 4, ratio: 0.75, label: "sign, peeling"  },
      { color: 7, ratio: 1.50, label: "walkway"        },
      { color: 3, ratio: 1.00, label: "shutter closed" },
      { color: 2, ratio: 1.20, label: "umeda under"    },
      { color: 4, ratio: 1.10, label: "taxi rank"      },
      { color: 3, ratio: 0.90, label: "return"         },
    ],
  },
  {
    id: "j09",
    title: "Room 402",
    place: "Tokyo studio",
    date: "2024.02",
    tag: "portrait",
    cover: { color: 7, ratio: 1.25 },
    words: "A small set of portraits for a friend. One window, one softbox as fill, a chair borrowed from the hallway. Her, reading between frames. We finished in an hour.",
    photos: [
      { color: 7, ratio: 1.25, label: "m. / 14:02" },
      { color: 3, ratio: 1.00, label: "profile"    },
      { color: 7, ratio: 0.80, label: "hands"      },
      { color: 4, ratio: 1.50, label: "chair"      },
      { color: 3, ratio: 1.20, label: "looking up" },
      { color: 7, ratio: 1.10, label: "last frame" },
    ],
  },
];

const OTHER = [
  { y: "2025", t: "Risograph Zine — vol.03",      d: "Self-published, 32pp, 2-color",      m: "print" },
  { y: "2025", t: "Type × Photo — exhibition",    d: "Group show, Nakameguro",             m: "show" },
  { y: "2024", t: "Darkroom Notes",               d: "Analog contact sheets, ongoing",     m: "series" },
  { y: "2024", t: "Polaroid index",               d: "Accumulated instants, 2019–",        m: "archive" },
  { y: "2023", t: "Field Recording — Coast",      d: "Audio + photo companion piece",      m: "sound" },
];

const ABOUT_ROWS = [
  { y: "2026", t: "Freelance",               d: "Editorial, commercial, personal",        m: "current"   },
  { y: "2023", t: "Studio Kōkan",            d: "Staff photographer",                     m: "Tokyo"     },
  { y: "2021", t: "Assistant — N. Harada",   d: "Lighting, location, post",               m: "Tokyo"     },
  { y: "2019", t: "BA Visual Communication", d: "Musashino Art University",               m: "degree"    },
];

window.JOURNALS = JOURNALS;
window.OTHER = OTHER;
window.ABOUT_ROWS = ABOUT_ROWS;
